# Enhanced GPTCache Configuration

cache:
  size_mb: 100
  similarity_threshold: 0.8
  eviction_policy: lru

context:
  enabled: true
  window_size: 5
  divergence_threshold: 0.3
  embedding_model: sentence-transformers/all-MiniLM-L6-v2

pca:
  enabled: true
  target_dimensions: 128
  training_samples: 1000
  model_path: models/pca_model.pkl
  compression_threshold: 100

federated:
  enabled: true
  num_users: 10
  aggregation_frequency: 100
  learning_rate: 0.01
  initial_tau: 0.8

benchmark:
  output_dir: data/results
  query_count: 1000
  variants:
    - baseline
    - context
    - pca
    - tau
    - full
