name: enhanced-gptcache
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - jupyter>=1.0.0
  - pytest>=7.4.0
  - pyyaml>=6.0
  - psutil>=5.9.0
  - tqdm>=4.65.0
  - joblib>=1.3.0
  - pip:
    - gptcache>=0.1.43
    - sentence-transformers>=2.2.0
    - faiss-cpu>=1.7.4
    - pytest-benchmark>=4.0.0
    - pytest-cov>=4.1.0
    - black>=23.0.0
    - ruff>=0.0.280
    - mypy>=1.5.0
